database:
  host: "172.19.0.1"
  port: 3306
  database: "s1_s1_velocity"
  username: "u1_OwcFPkdQsK"
  password: "WoyTOS62p=VIAoqQ!MHcea=Y"
  pool_size: 10

# Mode Debug pour afficher les logs SQL dans la console
debug: false
